"""add indexes on hot-filtered columns

Revision ID: 50041afa99cf
Revises: 3a877e6ded8f
Create Date: 2026-07-27 21:13:21.576529

"""
from collections.abc import Sequence

from alembic import op

revision: str = '50041afa99cf'
down_revision: str | None = '3a877e6ded8f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointment_slots_doctor_id'), 'appointment_slots', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointment_slots_start_time'), 'appointment_slots', ['start_time'], unique=False)
    op.create_index(op.f('ix_appointment_slots_status'), 'appointment_slots', ['status'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_escalations_status'), 'escalations', ['status'], unique=False)
    op.create_index(op.f('ix_reminders_scheduled_at'), 'reminders', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_reminders_status'), 'reminders', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_patient_id'), 'workflow_runs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_patient_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_reminders_status'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_scheduled_at'), table_name='reminders')
    op.drop_index(op.f('ix_escalations_status'), table_name='escalations')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointment_slots_status'), table_name='appointment_slots')
    op.drop_index(op.f('ix_appointment_slots_start_time'), table_name='appointment_slots')
    op.drop_index(op.f('ix_appointment_slots_doctor_id'), table_name='appointment_slots')
    # ### end Alembic commands ###
