"""add workflow run documents, doctor assignment, document summary

Revision ID: 93154fdf88a5
Revises: 50041afa99cf
Create Date: 2026-07-28 17:02:37.037383

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '93154fdf88a5'
down_revision: str | None = '50041afa99cf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_run_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_run_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['patient_documents.id'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_run_id', 'document_id', name='uq_workflow_run_document')
    )
    op.create_index(op.f('ix_workflow_run_documents_document_id'), 'workflow_run_documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_workflow_run_documents_workflow_run_id'), 'workflow_run_documents', ['workflow_run_id'], unique=False)
    op.add_column('patient_documents', sa.Column('summary', sa.String(length=2000), nullable=True))
    op.add_column('patient_documents', sa.Column('summary_generated_at', sa.DateTime(timezone=True), nullable=True))
    # SQLite has no ALTER-based support for adding a foreign key to an existing table —
    # batch mode recreates the table with a copy-and-move strategy instead.
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_doctor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(
            sa.Column('assignment_note', sa.String(length=500), nullable=False, server_default='')
        )
        batch_op.create_foreign_key(
            'fk_workflow_runs_assigned_doctor_id_doctors', 'doctors', ['assigned_doctor_id'], ['id']
        )
        batch_op.create_foreign_key(
            'fk_workflow_runs_assigned_by_users', 'users', ['assigned_by'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_workflow_runs_assigned_by_users', type_='foreignkey')
        batch_op.drop_constraint('fk_workflow_runs_assigned_doctor_id_doctors', type_='foreignkey')
        batch_op.drop_column('assignment_note')
        batch_op.drop_column('assigned_at')
        batch_op.drop_column('assigned_by')
        batch_op.drop_column('assigned_doctor_id')
    op.drop_column('patient_documents', 'summary_generated_at')
    op.drop_column('patient_documents', 'summary')
    op.drop_index(op.f('ix_workflow_run_documents_workflow_run_id'), table_name='workflow_run_documents')
    op.drop_index(op.f('ix_workflow_run_documents_document_id'), table_name='workflow_run_documents')
    op.drop_table('workflow_run_documents')
    # ### end Alembic commands ###
